## Classification Trees

```{r}
options(tidyverse.quiet = TRUE)
library(titanic)
library(tidyverse)
library(mice) #package for imputation
library(VIM) #visualizing missingness
library(rpart) #for classification trees
library(RColorBrewer) #better visualization of classification trees
library(rattle) #better visualization of classification trees
```

Read in dataset   
```{r}
titanic = titanic::titanic_train
```
Structure and summary
```{r}
str(titanic)
summary(titanic)
```

Factor conversion and recoding  
```{r}
titanic = titanic %>% mutate(Survived = as.factor(Survived)) %>% 
  mutate(Survived = fct_recode(Survived, "No" = "0", "Yes" = "1" )) %>%
  mutate(Pclass = as.factor(Pclass)) %>% mutate(Sex = as.factor(Sex)) %>%
  mutate(Embarked = as.factor(Embarked)) %>% 
  mutate(Embarked = fct_recode(Embarked,"Unknown"="","Cherbourg"="C","Southampton"="S","Queenstown"="Q"))

titanic$Cabin[titanic$Cabin==""] = NA #convert blanks in cabin to NA

str(titanic)
```

Column-wise deletion of the "Cabin" variable.  
```{r}
titanic = titanic %>% select(-Cabin) 
vim_plot = aggr(titanic, numbers = TRUE, prop = c(TRUE, FALSE),cex.axis=.7)
```

```{r}
#select only variables relevant to our analysis
titanic = titanic %>% select(c("Survived","Pclass","Sex","Age","SibSp","Parch","Embarked"))

imp_age = mice(titanic, m=1, method='pmm', printFlag=FALSE)
summary(imp_age)
```

Merge the imputed values into our titanic data frame  
```{r}
titanic_complete = complete(imp_age) 
summary(titanic_complete)
```

Now that we have the imputed/complete data, let's build a classification tree.  
```{r}
tree1 = rpart(Survived ~., titanic_complete, method="class")
fancyRpartPlot(tree1)
```
```{r}
printcp(tree1)
plotcp(tree1)
```








